### ISSUE TITLE
Obsolete init-values for secrets?

### ISSUE THREAD

**Issue by piejanssens** [SAP-samples/cloud-function-nodejs-samples#3]
Referring to https://github.com/SAP/cloud-function-nodejs-samples/tree/master/examples/hello-secret

I don't see a difference in deploying between:
```

faas-sdk init-values -y values.yaml
 faas-cli project deploy -y ./deploy/values.yaml -s <FAAS_SERVICE> -k <FAAS_KEY> -v
````

or just running:
```
 faas-cli project deploy -s <FAAS_SERVICE> -k <FAAS_KEY> -v
````
That second also seem to create the secrets in the same way.
Is there any specific reason for the documented approach in the example?

**Comment by Henrike42** [comment]
``
faas-sdk init-values -y values.yaml
``
generates an initial values.yaml file corresponding to the secret and config structure of the current project.
If you don't adapt values in the values.yaml then the following commands are the same:

``
faas-cli project deploy -y ./deploy/values.yaml -s <FAAS_SERVICE> -k <FAAS_KEY> -v
``
or 
``
faas-cli project deploy -s <FAAS_SERVICE> -k <FAAS_KEY> -v
``

**Comment by piejanssens** [comment]
Thanks @Henrike42 

Wrong place to ask, but I try anyway since I don't get a reaction from SCP contact channels:

- The service itself will it keep the name 'Functions' as it still does now in the SCP trial accounts?
- When will the service 'Functions' be out of 'beta' in the trail accounts?
- I cannot get the WebIDE to work properly to deploy a function in the right place. It gets deployed, works, but doesn't exist according to the Functions service instance in SCP... (CF API endpoint is correct). Whom to contact for this issue?

**Comment by Henrike42** [comment]
Regarding your questions:
• The service itself will it keep the name 'Functions' as it still does now in the SCP trial accounts?

No, the technical service name is xfs-runtime. From product point-of-view it is SAP Cloud Platform Extension Factory, serverless runtimes where functions is a sub component. 

• When will the service 'Functions' be out of 'beta' in the trail accounts?

The currently available Functions-service in trial will not go out of beta. But the new service ‘SAP CP Extension Factory, serverless runtime’ is offering more or less the same functionality (and more…) and is already available for productive usage as part of the CPEA license. We are working on bringing this service to trial as well. 

• I cannot get the WebIDE to work properly to deploy a function in the right place. It gets deployed, works, but doesn't exist according to the Functions service instance in SCP... (CF API endpoint is correct). Whom to contact for this issue?

You may open a BCP ticket on the component OPU-GW-OD-FUN with a detailed description and information.

**Comment by piejanssens** [comment]
> You may open a BCP ticket on the component OPU-GW-OD-FUN with a detailed description and information.

Incident 91498 / 2020
